# Use the official Node.js image as a base
FROM node:18.20.2-alpine

# Set working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package*.json .
RUN npm i

# Copy the rest of the app files into the container
COPY . .

# Expose port for the backend server
EXPOSE 5100

# Run the Express server
CMD ["npm", "run", "dev"]
