FROM node:20.18.0
#18.20.2-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./
RUN npm i

# Copy the rest of the server files into the container
COPY . .

# Expose the port the server runs on
EXPOSE 5200

# Command to run the server
CMD ["npx", "nodemon", "--legacy-watch", "server.js"]