name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch: # Add this line to enable manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Export Environment Variables
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
      run: |
        echo DB_HOST=$DB_HOST >> ./server/.env
        echo DB_USER=$DB_USER >> ./server/.env
        echo DB_PASSWORD=$DB_PASSWORD >> ./server/.env
        echo DB_NAME=$DB_NAME >> ./server/.env

    - name: Set up Docker Buildx
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker buildx create --use
        docker buildx inspect --bootstrap

    - name: Build Docker image
      run: |
        docker login -u lmerta -p ${{ secrets.DOCKER_PASSWORD }}
        docker buildx build -t lmerta/web-server-admin:latest --push .

    - name: Setup SSH key
      env:
        DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$DEPLOY_SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
    - name: Deploy Docker image to server
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no deploy@mertalukas.cz << 'EOF'
          docker stop web-server-admin-cont || true && docker rm web-server-admin-cont || true
          docker rmi lmerta/web-server-admin:latest || true
          docker pull lmerta/web-server-admin:latest
          docker run -dp 6010:5200 --name web-server-admin-cont --restart unless-stopped lmerta/web-server-admin:latest
        EOF
